name: CI Java 18 App using SonarQube

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout source code
      - name: Code Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0      # 2. Setup Java 18
      - name: Set up JDK 18
        uses: actions/setup-java@v6
        with:
          java-version: '18'
          distribution: 'temurin'
          cache: maven

      # 3. Verify Java version
      - name: Check Java Version
        run: |
          java -version
          mvn -version
          
